// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsXJJQW0sM4wFaIwbmMvCIElY9YO1avAA',
    appId: '1:773454250682:web:886664dc0903449f96b883',
    messagingSenderId: '773454250682',
    projectId: 'alma-83c9f',
    authDomain: 'alma-83c9f.firebaseapp.com',
    storageBucket: 'alma-83c9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFFFulHiR9X1tyzPiaT_Ay9XWVd9-nN4I',
    appId: '1:773454250682:android:6d1fb599014794b496b883',
    messagingSenderId: '773454250682',
    projectId: 'alma-83c9f',
    storageBucket: 'alma-83c9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByF-gcYe-hTD_9owhlCG8Jnmf1lNyzkRg',
    appId: '1:773454250682:ios:3cc53e50795b6a3896b883',
    messagingSenderId: '773454250682',
    projectId: 'alma-83c9f',
    storageBucket: 'alma-83c9f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByF-gcYe-hTD_9owhlCG8Jnmf1lNyzkRg',
    appId: '1:773454250682:ios:3cc53e50795b6a3896b883',
    messagingSenderId: '773454250682',
    projectId: 'alma-83c9f',
    storageBucket: 'alma-83c9f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsXJJQW0sM4wFaIwbmMvCIElY9YO1avAA',
    appId: '1:773454250682:web:fb5c2d91caf1ceca96b883',
    messagingSenderId: '773454250682',
    projectId: 'alma-83c9f',
    authDomain: 'alma-83c9f.firebaseapp.com',
    storageBucket: 'alma-83c9f.firebasestorage.app',
  );
}
